name: faq_app
description: an app to pass assessment for interviewing
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_form_builder: ^8.0.0
  form_builder_validators: ^8.6.1
  get_it: ^7.5.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
